sudo: false
language: node_js
cache:
  directories:
    - node_modules
    - jspm_packages
notifications:
  email: false
node_js:
  - '5'
before_install:
  - npm install -g jspm
  - jspm install
before_script:
  - npm prune
script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm test
  - npm run build
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
